apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-experiment
spec:
  params:
    - name: baseline
      type: string
      description: Unique id of the baseline model version
    - name: candidate
      type: string
      description: Unique id of the candidate model version
  resources:
    outputs:
      - name: modelImage
        type: image
  steps:
    - name: canary-experiment
      image: docker.io/iter8/kfserving-cli
      command: ["kubectl", "iter8", "create-experiment"]
      args:
        - --baseline=$(params.baseline)
        - --candidate=$(params.candidate)
        - --termination_webhook=$(params.cloudevent_sink_url)
    workspaces:
      - name: modelRoot
        description: The folder where model folder will be created
        mountPath: /path/to/model/dir
