configMapGenerator:
- name: iter8-metrics
  files:
  - revision-metrics.json
  - cadvisor-metrics.json
- name: schemas-and-transforms
  files:
  - schemas-and-transforms.json
generatorOptions:
  disableNameSuffixHash: true