apiVersion: iter8.tools/v1alpha3
kind: Handler
metadata:
  name: start-handler
spec: # this is a kubernetes raw extension type. Tomorrow, you can replace job with tekton task if you want.
  apiVersion: batch/v1
  kind: Job
  metadata:
    name: $experiment.name-start
  spec:
    template:
      spec:
        containers:
        - name: start
          image: iter8-kfserving
          command:
          - /handlers/scripts/start.sh
          env:
          - name: EXPERIMENT_NAME
            value: $experiment.name
        restartPolicy: OnFailure
    backoffLimit: 4