namePrefix: iter8-

resources:
- github.com/sriumcp/iter8-analytics/install/kubernetes/kustomize/?ref=install

configMapGenerator:
- name: analytics
  files:
  - config.yaml
generatorOptions:
  disableNameSuffixHash: true  