namePrefix: iter8-

resources:
- https://raw.githubusercontent.com/iter8-tools/iter8-analytics/install/install/kubernetes/kustomize/service.yaml
- https://raw.githubusercontent.com/iter8-tools/iter8-analytics/install/install/kubernetes/kustomize/deployment.yaml

configMapGenerator:
- name: analytics
  files:
  - config.yaml
generatorOptions:
  disableNameSuffixHash: true  