apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: sklearn-iris
spec:
  default:
    predictor:
      tensorflow:
        storageUri: gs://kfserving-samples/models/tensorflow/flowers